apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\doal\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: customers-service
  name: customers-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customers-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\doal\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: customers-service
    spec:
      containers:
        - image: springcommunity/spring-petclinic-customers-service
          imagePullPolicy: IfNotPresent
          name: customers-service
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
status: {}
