---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:  
  - name: http
    port: 8080
    nodePort: 30036
    protocol: TCP
