---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  annotations:
    mesh.traefik.io/ratelimit-average: "10"
    mesh.traefik.io/ratelimit-burst: "10"
spec:
  ports:
  - name: "http"
    port: 8080
    # appProtocol: "http"
    targetPort: 8080
  selector:
    app: customers-service
status:
  loadBalancer: {}
